name: canonical-doc-utils
version: '0.2.16' 
summary: tools for working with Canonical docs repositories
description: |
  This provides a number of commands for dealing with documentation 
  repositories built with documentation-builder
grade: stable 
confinement: classic
icon: images/docs-logo.svg
apps:
  backport:
    command: bin/docs-backport
  cleanfork:
    command: bin/docs-cleanfork
  juju-commandgen:
    command: bin/docs-juju-commandgen
parts:
  canonical-doc-utils:
    plugin: python
    source: https://github.com/canonical-documentation/canonical-doc-utils.git

